/* "Wir zwei": the questions. Pure data – used in the browser (window.DuoContent) and by the
   node tests (module.exports). Ids never change, so stored answers keep pointing at their question. */
(function () {
  /* Frage des Tages: everyone picks their own answer and guesses the other's */
  const DAILY = [
    ["d01", "Was wäre der perfekte gemeinsame Sonntag?", ["Ausschlafen & Brunch", "Ausflug in die Natur", "Couch & Serien", "Stadt erkunden"]],
    ["d02", "Was würdest du mit 1.000 € spontan machen?", ["Sofort verreisen", "Schick essen gehen", "Sparen", "Etwas Schönes für dich kaufen"]],
    ["d03", "Welches Urlaubsziel reizt dich gerade am meisten?", ["Strand & Meer", "Berge", "Große Stadt", "Roadtrip ins Blaue"]],
    ["d04", "Wie startest du am liebsten in den Tag?", ["Kaffee in Ruhe", "Sport", "So lange wie möglich schlafen", "Mit einer Nachricht von dir"]],
    ["d05", "Was ist dein liebstes Date?", ["Kochen zu Hause", "Kino", "Picknick", "Restaurant ausprobieren"]],
    ["d06", "Welches Essen könntest du jeden Tag essen?", ["Pizza", "Pasta", "Sushi", "Tapas"]],
    ["d07", "Wie verbringst du einen Regentag am liebsten?", ["Film & Decke", "Ein Buch", "Backen", "Trotzdem raus"]],
    ["d08", "Welche Superkraft hättest du gern?", ["Teleportieren", "Gedanken lesen", "Zeit anhalten", "Fliegen"]],
    ["d09", "Was nervt dich am meisten?", ["Unpünktlichkeit", "Lautes Schmatzen", "Langsames WLAN", "Leere Akkus"]],
    ["d10", "Welche Musik läuft bei dir gerade am meisten?", ["Pop", "Rock/Indie", "Elektro", "Spanisch/Latin"]],
    ["d11", "Was ist dir an einem Geschenk am wichtigsten?", ["Die Idee dahinter", "Selbstgemacht", "Etwas Nützliches", "Eine gemeinsame Erfahrung"]],
    ["d12", "Wo würdest du am liebsten mal mit mir wohnen?", ["Am Meer", "In einer Großstadt", "Auf dem Land", "Mal hier, mal da"]],
    ["d13", "Was ist dein liebstes Getränk am Abend?", ["Wein", "Bier", "Cocktail", "Tee"]],
    ["d14", "Welches Tier wärst du?", ["Katze", "Hund", "Delfin", "Faultier"]],
    ["d15", "Wie zeigst du am liebsten Liebe?", ["Worte", "Zeit zusammen", "Kleine Geschenke", "Kuscheln"]],
    ["d16", "Welche Jahreszeit ist deine?", ["Frühling", "Sommer", "Herbst", "Winter"]],
    ["d17", "Was machst du als Erstes nach einem langen Tag?", ["Hinlegen", "Duschen", "Essen", "Mit dir telefonieren"]],
    ["d18", "Welches Abenteuer sollten wir als Nächstes erleben?", ["Fallschirmspringen", "Interrail", "Tauchen lernen", "Festival"]],
    ["d19", "Was ist dein Guilty Pleasure?", ["Reality-TV", "Süßes um Mitternacht", "Stundenlang scrollen", "Schlager mitsingen"]],
    ["d20", "Welche Serie würdest du sofort nochmal schauen?", ["Eine Komödie", "Ein Krimi", "Fantasy", "Eine Doku"]],
    ["d21", "Wie bist du auf Partys?", ["Tanzfläche", "In der Küche quatschen", "Früh nach Hause", "DJ-Wünsche abgeben"]],
    ["d22", "Was ist dein liebster Snack?", ["Chips", "Schokolade", "Obst", "Nüsse"]],
    ["d23", "Was würdest du an einem freien Tag allein machen?", ["Wellness", "Shoppen", "Sport", "Gar nichts"]],
    ["d24", "Was schätzt du an uns am meisten?", ["Wir lachen viel", "Wir reden über alles", "Wir sind ein Team", "Es knistert noch"]],
    ["d25", "Welche Reise-Art passt zu dir?", ["Alles planen", "Spontan treiben lassen", "All inclusive", "Rucksack & Hostel"]],
    ["d26", "Wie streitest du?", ["Sofort ausdiskutieren", "Erst abkühlen", "Mit Humor", "Ich gebe schnell nach"]],
    ["d27", "Was ist dein Lieblingsort zu Hause?", ["Sofa", "Bett", "Küche", "Balkon"]],
    ["d28", "Welches Dessert gewinnt?", ["Tiramisu", "Eis", "Churros", "Käsekuchen"]],
    ["d29", "Was würdest du lieber können?", ["Ein Instrument", "Eine neue Sprache", "Richtig gut kochen", "Tanzen"]],
    ["d30", "Wie feierst du deinen Geburtstag am liebsten?", ["Große Party", "Kleines Essen", "Mit dir allein", "Gar nicht groß"]],
    ["d31", "Welches Wetter macht dich am glücklichsten?", ["Sonne & 25 Grad", "Gewitter", "Schnee", "Frischer Herbsttag"]],
    ["d32", "Was ist dir in einer Beziehung am wichtigsten?", ["Vertrauen", "Humor", "Nähe", "Freiraum"]],
    ["d33", "Womit kann man dich immer aufmuntern?", ["Essen", "Einer Umarmung", "Einem Witz", "Einer Überraschung"]],
    ["d34", "Was wärst du in einem Film?", ["Held:in", "Comic-Sidekick", "Bösewicht:in", "Die weise Stimme"]],
    ["d35", "Wie sieht dein perfekter Abend aus?", ["Kerzen & Wein", "Spieleabend", "Ausgehen", "Früh schlafen"]],
    ["d36", "Was würdest du nie teilen?", ["Pommes", "Die Decke", "Dein Ladekabel", "Ich teile alles mit dir"]],
    ["d37", "Welcher Sport passt zu uns?", ["Wandern", "Tennis", "Yoga", "Fernseh-Sport"]],
    ["d38", "Was ist deine größte Stärke?", ["Geduld", "Humor", "Organisation", "Spontaneität"]],
    ["d39", "Wie schreibst du am liebsten mit mir?", ["Lange Nachrichten", "Sprachnachrichten", "Memes", "Emojis"]],
    ["d40", "Was würdest du an unserem Jahrestag machen?", ["Wegfahren", "Fancy Dinner", "Den ersten Date-Ort besuchen", "Etwas ganz Neues"]],
    ["d41", "Wann bist du am kreativsten?", ["Morgens", "Mittags", "Abends", "Mitten in der Nacht"]],
    ["d42", "Welches Spiel gewinnst du gegen mich?", ["Cabo", "6 nimmt!", "Qwixx", "Wer von uns beiden?"]]
  ].map(([id, text, options]) => ({ id, text, options }));

  /* Wer von uns beiden? – both tap Isi or Benji, then we see where we agree */
  const WHO = [
    "Wer von uns beiden kocht besser?",
    "Wer von uns beiden ist morgens schneller fertig?",
    "Wer von uns beiden schreibt zuerst „Ich liebe dich“?",
    "Wer von uns beiden verliert öfter beim Spielen?",
    "Wer von uns beiden hat den besseren Musikgeschmack?",
    "Wer von uns beiden ist eifersüchtiger?",
    "Wer von uns beiden lacht über die eigenen Witze?",
    "Wer von uns beiden schläft zuerst ein?",
    "Wer von uns beiden hat mehr Schuhe?",
    "Wer von uns beiden ist der bessere Beifahrer?",
    "Wer von uns beiden plant die Urlaube?",
    "Wer von uns beiden entschuldigt sich zuerst?",
    "Wer von uns beiden ist abenteuerlustiger?",
    "Wer von uns beiden ist romantischer?",
    "Wer von uns beiden isst den letzten Bissen?",
    "Wer von uns beiden hört schlechter zu?",
    "Wer von uns beiden würde in einer Zombie-Apokalypse länger überleben?",
    "Wer von uns beiden ist ordentlicher?",
    "Wer von uns beiden weint bei Filmen?",
    "Wer von uns beiden hat den gefährlicheren Hunger („hangry“)?",
    "Wer von uns beiden ist schlechter im Geheimnisse-Behalten?",
    "Wer von uns beiden könnte länger ohne Handy?",
    "Wer von uns beiden ist schneller genervt?",
    "Wer von uns beiden tanzt besser?",
    "Wer von uns beiden ist der größere Kuschelbär?",
    "Wer von uns beiden kauft mehr unnötige Dinge?",
    "Wer von uns beiden kommt öfter zu spät?",
    "Wer von uns beiden ist mutiger?",
    "Wer von uns beiden ist besser im Fotos-Machen?",
    "Wer von uns beiden würde bei „Wer wird Millionär“ weiter kommen?",
    "Wer von uns beiden schnarcht lauter?",
    "Wer von uns beiden ist das größere Naschkätzchen?",
    "Wer von uns beiden hat die schlechtere Orientierung?",
    "Wer von uns beiden macht die besseren Geschenke?",
    "Wer von uns beiden ist dramatischer, wenn er/sie krank ist?",
    "Wer von uns beiden hat sich zuerst verliebt?",
    "Wer von uns beiden bringt den anderen öfter zum Lachen?",
    "Wer von uns beiden ist der/die Sportlichere?",
    "Wer von uns beiden ist sturer?",
    "Wer von uns beiden würde eher einen Hund adoptieren?",
    "Wer von uns beiden verbringt mehr Zeit im Bad?",
    "Wer von uns beiden ist spontaner?",
    "Wer von uns beiden ist besser im Streit-Gewinnen?",
    "Wer von uns beiden ist das größere Plappermaul?",
    "Wer von uns beiden ist der bessere Lehrer/die bessere Lehrerin?",
    "Wer von uns beiden hat das verrücktere Hobby?",
    "Wer von uns beiden würde eher eine Wohnung voller Pflanzen haben?",
    "Wer von uns beiden ist morgens grummeliger?"
  ];

  /* Hot oder Not? – both vote 🔥 or ❄️ */
  const HOTNOT = [
    "🍍 Ananas auf Pizza", "🏕️ Campen im Zelt", "🧳 Spontaner Wochenendtrip", "🌅 Sonnenaufgang anschauen",
    "🎤 Karaoke-Abend", "🧗 Bouldern gehen", "🎢 Achterbahn fahren", "🛁 Gemeinsam baden",
    "🍣 Sushi-Date", "🏖️ All-inclusive-Urlaub", "📵 Ein Tag ohne Handy", "🎬 Horrorfilm-Marathon",
    "🥾 Wandern in den Bergen", "🍷 Weinprobe", "🧘 Pärchen-Yoga", "🎲 Spieleabend mit Freunden",
    "🐕 Ein gemeinsamer Hund", "🍳 Frühstück im Bett", "🚐 Roadtrip im Van", "🎆 Silvester auf einer großen Party",
    "🧁 Zusammen backen", "🏊 Eisbaden", "💃 Tanzkurs zu zweit", "🎨 Malen nach Zahlen",
    "📸 Pärchen-Fotoshooting", "🎧 Podcast zusammen hören", "🏃 Morgens joggen", "🛍️ Shopping-Tag",
    "🍿 Kino in der letzten Reihe", "🧩 1000-Teile-Puzzle", "🌶️ Extrem scharfes Essen", "🎮 Zocken bis spät",
    "🚲 Fahrradtour", "🛶 Kanufahren", "🎟️ Festival-Wochenende", "🌧️ Spaziergang im Regen",
    "🥂 Fancy Rooftop-Bar", "🍕 Pizza selber machen", "🧖 Wellness-Tag", "🏝️ Auswandern nach Spanien",
    "🎁 Überraschungsgeschenke", "📚 Gemeinsam ein Buch lesen", "🕺 Disco der 80er", "🐠 Schnorcheln",
    "⛷️ Skiurlaub", "🍜 Streetfood-Tour", "🛫 Last-Minute-Flug ins Ungewisse", "💌 Handgeschriebene Briefe",
    "🏡 Haus auf dem Land", "🌃 Großstadt-Wohnung", "🧗‍♀️ Klettersteig", "🎳 Bowling-Abend",
    "🦄 Mottoparty mit Kostüm", "🌌 Sterne gucken", "🍦 Eis zum Frühstück", "🏋️ Zusammen ins Fitnessstudio"
  ];

  const api = { DAILY, WHO, HOTNOT };
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  if (typeof window !== "undefined") window.DuoContent = api;
})();
