create table if not exists public.qwixx_games (
  id bigint generated by default as identity primary key,
  status text not null default 'waiting',
  host_person text not null,
  guest_person text,
  state jsonb not null default '{}'::jsonb,
  -- both players cross the white sum at the same time; writes are guarded by this counter
  version integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.qwixx_games enable row level security;

drop policy if exists "Allow everyone to read" on public.qwixx_games;
create policy "Allow everyone to read"
  on public.qwixx_games for select
  using (true);

drop policy if exists "Allow everyone to insert" on public.qwixx_games;
create policy "Allow everyone to insert"
  on public.qwixx_games for insert
  with check (true);

drop policy if exists "Allow everyone to update" on public.qwixx_games;
create policy "Allow everyone to update"
  on public.qwixx_games for update
  using (true)
  with check (true);

drop policy if exists "Allow everyone to delete" on public.qwixx_games;
create policy "Allow everyone to delete"
  on public.qwixx_games for delete
  using (true);

alter publication supabase_realtime add table public.qwixx_games;
