-- "Nur für uns": links we share with each other, a 1–5 rating from each of us and comments.
create table if not exists public.private_links (
  id bigint generated by default as identity primary key,
  url text not null check (url ~* '^https?://' and char_length(url) <= 2000),
  title text check (title is null or char_length(title) <= 120),
  added_by text not null,
  rating_isi smallint check (rating_isi between 1 and 5),
  rating_benji smallint check (rating_benji between 1 and 5),
  created_at timestamptz not null default now()
);

create table if not exists public.private_link_comments (
  id bigint generated by default as identity primary key,
  link_id bigint not null references public.private_links (id) on delete cascade,
  author text not null,
  body text not null check (char_length(body) between 1 and 500),
  created_at timestamptz not null default now()
);

create index if not exists private_link_comments_link_idx on public.private_link_comments (link_id, created_at);

alter table public.private_links enable row level security;
alter table public.private_link_comments enable row level security;

create policy "Allow everyone to read" on public.private_links for select using (true);
create policy "Allow everyone to insert" on public.private_links for insert with check (true);
create policy "Allow everyone to update" on public.private_links for update using (true) with check (true);
create policy "Allow everyone to delete" on public.private_links for delete using (true);

create policy "Allow everyone to read" on public.private_link_comments for select using (true);
create policy "Allow everyone to insert" on public.private_link_comments for insert with check (true);
create policy "Allow everyone to delete" on public.private_link_comments for delete using (true);

alter publication supabase_realtime add table public.private_links;
alter publication supabase_realtime add table public.private_link_comments;
