create table if not exists public.cabo_games (
  id bigint generated by default as identity primary key,
  status text not null default 'waiting',
  host_person text not null,
  guest_person text,
  state jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.cabo_games enable row level security;

drop policy if exists "Allow everyone to read" on public.cabo_games;
create policy "Allow everyone to read"
  on public.cabo_games for select
  using (true);

drop policy if exists "Allow everyone to insert" on public.cabo_games;
create policy "Allow everyone to insert"
  on public.cabo_games for insert
  with check (true);

drop policy if exists "Allow everyone to update" on public.cabo_games;
create policy "Allow everyone to update"
  on public.cabo_games for update
  using (true)
  with check (true);

drop policy if exists "Allow everyone to delete" on public.cabo_games;
create policy "Allow everyone to delete"
  on public.cabo_games for delete
  using (true);
