create table if not exists public.watchlist (
  id bigint generated by default as identity primary key,
  title text not null,
  media_type text not null default 'film',
  platform text,
  added_by text,
  watched boolean not null default false,
  rating smallint,
  created_at timestamptz not null default now(),
  watched_at timestamptz
);

alter table public.watchlist add column if not exists media_type text not null default 'film';
alter table public.watchlist add column if not exists platform text;
alter table public.watchlist add column if not exists added_by text;
alter table public.watchlist add column if not exists watched boolean not null default false;
alter table public.watchlist add column if not exists rating smallint;
alter table public.watchlist add column if not exists created_at timestamptz not null default now();
alter table public.watchlist add column if not exists watched_at timestamptz;

alter table public.watchlist enable row level security;

drop policy if exists "Allow everyone to read" on public.watchlist;
create policy "Allow everyone to read"
  on public.watchlist for select
  using (true);

drop policy if exists "Allow everyone to insert" on public.watchlist;
create policy "Allow everyone to insert"
  on public.watchlist for insert
  with check (true);

drop policy if exists "Allow everyone to update" on public.watchlist;
create policy "Allow everyone to update"
  on public.watchlist for update
  using (true)
  with check (true);

drop policy if exists "Allow everyone to delete" on public.watchlist;
create policy "Allow everyone to delete"
  on public.watchlist for delete
  using (true);
