-- Kisses, hugs, hearts and short notes that Mochi carries from one of us to the other.
create table if not exists public.mochi_messages (
  id bigint generated by default as identity primary key,
  from_person text not null,
  to_person text not null,
  kind text not null check (kind in ('kiss', 'hug', 'heart', 'note')),
  note text check (note is null or char_length(note) <= 140),
  created_at timestamptz not null default now(),
  delivered_at timestamptz
);

create index if not exists mochi_messages_to_person_idx on public.mochi_messages (to_person, created_at desc);

alter table public.mochi_messages enable row level security;

create policy "Allow everyone to read"
  on public.mochi_messages for select
  using (true);

create policy "Allow everyone to insert"
  on public.mochi_messages for insert
  with check (true);

create policy "Allow everyone to update"
  on public.mochi_messages for update
  using (true)
  with check (true);

alter publication supabase_realtime add table public.mochi_messages;
