-- "Wir zwei": answers to the question of the day (one per person and day) and the
-- live rounds of "Wer von uns beiden?" / "Hot oder Not?" (game-room.js, two players)
create table if not exists public.daily_answers (
  id bigint generated by default as identity primary key,
  day date not null,
  person text not null check (person in ('Isi', 'Benji')),
  question_id text not null,
  answer smallint not null check (answer between 0 and 3),
  guess smallint not null check (guess between 0 and 3),
  created_at timestamptz not null default now(),
  unique (day, person)
);
alter table public.daily_answers enable row level security;
create policy "Allow everyone to read" on public.daily_answers for select using (true);
create policy "Allow everyone to insert" on public.daily_answers for insert with check (true);

create table if not exists public.duo_games (
  id bigint generated by default as identity primary key,
  status text not null default 'waiting',
  host_person text not null,
  guest_person text,
  state jsonb not null default '{}'::jsonb,
  version integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.duo_games enable row level security;
create policy "Allow everyone to read" on public.duo_games for select using (true);
create policy "Allow everyone to insert" on public.duo_games for insert with check (true);
create policy "Allow everyone to update" on public.duo_games for update using (true) with check (true);
create policy "Allow everyone to delete" on public.duo_games for delete using (true);

alter publication supabase_realtime add table public.daily_answers;
alter publication supabase_realtime add table public.duo_games;
